name: antispam

on:
  issues:
    types:
      - opened
      - edited
      - reopened
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  pull-requests: write
  issues: write

jobs:
  build:
    name: Antispam
    runs-on: ubuntu-latest

    steps:
      - uses: liamg/antispam-action@1
        with:
          token: ${{ github.token }}
